# REMEMBER rename the file in terraform.tfvars fill in and put in .gitignore
AWS_ACCESS_KEY = ""
AWS_SECRET_KEY = ""
AWS_REGION     = ""
RDS_PASSWORD   = ""
PATH_TO_PRIVATE_KEY = ""
PATH_TO_PUBLIC_KEY = ""
RDS_USER = ""
RDS_NAME = ""
OFFICE_IP = ""
HOME_IP = ""